CREATE DATABASE EJSBLOG;

CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    IMG_URL TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);